kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: embeddings-pvc
  namespace: neural-search-prod
spec:
  accessModes:
  - ReadOnlyMany 
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
