apiVersion: v1
kind: PersistentVolume
metadata:
  name: embeddings-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: neural-search-prod
    name: embeddings-pvc
  gcePersistentDisk:
    pdName: disk-1
    fsType: ext4
