kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: embeddings-pvc
  namespace: neural-search-prod
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10G
  volumeName: embeddings-pv
