apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: embeddings-pvc
  namespace: neural-search-prod
  labels:
    type: local
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: embeddings-storage

