apiVersion: v1
data:
  REGISTER_NON_INTERACTIVE: "true"
  REGISTER_LOCKED: "false"
  METRICS_SERVER: "0.0.0.0:9100"
  #CI_SERVER_URL: "https://neuralsearch.com/ci"
  #RUNNER_REQUEST_CONCURRENCY: "4"
  #RUNNER_EXECUTOR: "kubernetes"
  KUBERNETES_NAMESPACE: "neural-search-prod"
  KUBERNETES_PRIVILEGED: "true"
  KUBERNETES_CPU_LIMIT: "500m"
  KUBERNETES_CPU_REQUEST: "100m"
  KUBERNETES_MEMORY_LIMIT: "512Mi"
  KUBERNETES_SERVICE_CPU_LIMIT: "1"
  KUBERNETES_SERVICE_MEMORY_LIMIT: "1Gi"
  KUBERNETES_HELPER_CPU_LIMIT: "500m"
  KUBERNETES_HELPER_MEMORY_LIMIT: "100Mi"
  KUBERNETES_PULL_POLICY: "if-not-present"
  KUBERNETES_TERMINATIONGRACEPERIODSECONDS: "10"
  KUBERNETES_POLL_INTERVAL: "5"
  KUBERNETES_POLL_TIMEOUT: "360"
kind: ConfigMap
metadata:
  labels:
    app: neural-serch
  name: neural-search-cm
  namespace: neural-search-prod
