version: "3.8.0"

services:
  web:
    build: .
    volumes:
      - ./:/usr/src/search/
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

volumes:
  postgres_data:
